### ISSUE TITLE
Regression when upgrading to 2.0.0

### ISSUE THREAD

**Issue by devnewton** [baptistedonaux/brunch-typescript#22]
I try to upgrade from 1.8.1 to 2.0.0 but compilation failed with a strange behavior:

- first brunch build give some detailed errors (2370, 2488, 2503...).
- next brunch build just print on error per file: _error: Compiling of [filename].ts failed._

My IDE (VSCode) dont give any error.

Here is my project code:

1.8.1 on master branch: https://github.com/devnewton/shmuprpg
2.0.0 on typescript2 branch: https://github.com/devnewton/shmuprpg/tree/typescript2

**Comment by colinbate** [comment]
Hi @devnewton 
If you are coming from version 1.8.1 then you've run into the issue which arose after surfacing the underlying TypeScript errors. You can read the README section for more information: https://github.com/baptistedonaux/brunch-typescript#errors

The bottom line, you can get back to what you had before with this in your `brunch-config` file:

```js
  plugins: {
    brunchTypescript: {
      ignoreErrors: true
    }
  }
```

**Comment by devnewton** [comment]
I've set the ignoreErrors parameter, but I still get these errors. Here is the exact shell command to reproduce:

git clone https://github.com/devnewton/shmuprpg t2-shmuprpg
git checkout typescript2
brunch build
brunch build

**Comment by colinbate** [comment]
You were absolutely correct, I had a typo in that code path when setting `ignoreErrors` to `true`. I've fixed it and pushed it in for version 2.0.1, but I'll need @baptistedonaux to publish the new version on npm.

**Comment by devnewton** [comment]
Thank you, I'll wait for @baptistedonaux release then!

**Comment by baptistedonaux** [comment]
Hey ! Thanks @devnewton for your issue and again thanks @colinbate for your fix !

Sorry for the response time, I published the new release 2.0.1 !
